version: '3'
services:
  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
    volumes:
     - ./data/redis:/data
    container_name: redis_db
    restart: always
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db