version: '3.2'
services:
  redis:
    image: redis:alpine
    ports:
     - "127.0.0.1:6379:6379"
    volumes:
     - ./data/redis:/data
    container_name: redis_db
    restart: always
  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./data/mongo:/data/db