version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'MeerBiene'
    assignees:
      - 'MeerBiene'
    commit-message:
      prefix: chore
      include: 'scope'
