name: 'Docgen'

on:
  push:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install Packages
        run: npm install common-tags
      - name: Generate Docs
        run: npm run docs
      - name: Commit and push Changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git diff --staged --quiet || git commit -m "ci (build | docs): generate docs for $GITHUB_SHA"
          git checkout develop
          git merge main
          git push --all
